### ISSUE TITLE
Seeing boat modifications and traits from DOTR as Careers?

### ISSUE THREAD

**Issue by simulacrum-1** [mcailleaux/WFRP4-FoundryVTT-wfrp4e-npc-generator#4] opened 2021-05-01 09:17 UTC
![Screenshot 2021-05-01 at 10 15 23](https://user-images.githubusercontent.com/68729767/116777835-71595c80-aa66-11eb-92be-d9484b018f13.jpg)
![Screenshot 2021-05-01 at 10 14 35](https://user-images.githubusercontent.com/68729767/116777836-73bbb680-aa66-11eb-809d-eb5b53bd6bd3.jpg)

**Comment by mcailleaux** [comment] 2021-05-01 09:54
I dont have those modules yet, I will test it when I buy it.

For the next release i will add a filter on item type because I think the cause is i take the careeres only by tag filtering

**Comment by mcailleaux** [comment] 2021-05-04 20:36
Resolved in the 1.3.0 version

**Closed by mcailleaux** 2021-05-04 20:36 UTC
